# Site title
title = "Andromeda"
base_url = "https://blog.andromeda.is"
description = "Photography journal theme for Zola"
compile_sass = true

[extra]
header_links = [
    {name = "Zola", url = "https://www.getzola.org/"},
    {name = "Blog", url = "https://blog.andromeda.is/"}
]
# favicon = "/images/favicon.ico"