# Site title
title = "Andromeda"
base_url = "https://andromeda-theme.netlify.app"
description = "Photography journal theme for Zola"
compile_sass = true

[extra]
header_links = [
    {name = "Zola", url = "https://www.getzola.org/"},
    {name = "Blog", url = "https://andromeda-theme.netlify.app"}
]
# favicon = "/images/favicon.ico"
