name = "Andromeda"
description = "Photography journal blog theme"
license = "MIT"
homepage = "https://github.com/Pixadus/andromeda-theme"
min_version = "0.4.0"

[author]
name = "Parker Lamb"
homepage = "https://blog.andromeda.is"